### ISSUE TITLE
mix talon.new crashes with argument error

### ISSUE THREAD

**Issue by surik** [ex-admin/ex_admin#82]
# Environment
```
$ elixir --version
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.5
```

# Behaviour
I'm using talon from `master` and just trying to add it to exist phoenix 1.3 application. 
```
$ mix talon.new
* creating config/talon.exs
* creating lib/tposs/talon/admin/admin.ex
* creating lib/tposs/talon/controllers/admin_resource_controller.ex
* creating lib/tposs/talon/controllers/admin_page_controller.ex
* creating lib/tposs/talon/admin/dashboard.ex
* creating lib/tposs/talon/web.ex
* creating lib/tposs/talon/messages.ex
Running talon.gen.theme
* creating lib/tposs/talon/views/admin/admin-lte/layout_view.ex
* creating lib/tposs/talon/templates/admin/admin-lte/layout/app.html.slim
* creating lib/tposs/talon/templates/admin/admin-lte/layout/nav_action_link.html.slim
* creating lib/tposs/talon/templates/admin/admin-lte/layout/nav_resource_link.html.slim
* creating lib/tposs/talon/templates/admin/admin-lte/layout/sidebar.html.slim
* creating lib/tposs/talon/templates/admin/admin-lte/dashboard/index.html.slim
* creating lib/tposs/talon/views/admin/admin-lte/dashboard_view.ex
* creating lib/tposs/talon/templates/admin/admin-lte/generators/edit.html.eex
* creating lib/tposs/talon/templates/admin/admin-lte/generators/form.html.eex
* creating lib/tposs/talon/templates/admin/admin-lte/generators/index.html.eex
* creating lib/tposs/talon/templates/admin/admin-lte/generators/new.html.eex
* creating lib/tposs/talon/templates/admin/admin-lte/generators/show.html.eex
* creating assets/static/images/talon/admin-lte/orderable.png
* creating assets/vendor/talon/admin-lte/plugins/jQuery/jquery-2.2.3.min.js
* creating assets/vendor/talon/admin-lte/bootstrap/js/bootstrap.min.js
* creating assets/vendor/talon/admin-lte/dist/js/app.min.js
* creating assets/css/talon/admin-lte/talon.css
* creating assets/js/talon/admin-lte/talon.js
* creating assets/vendor/talon/admin-lte/dist/css/skins/all-skins.css
* creating assets/vendor/talon/admin-lte/bootstrap/css/bootstrap.min.css
* creating assets/vendor/talon/admin-lte/dist/css/AdminLTE.min.css
* creating assets/vendor/talon/admin-lte/plugins/sweetalert/dist/sweetalert.min.js
* creating assets/vendor/talon/admin-lte/plugins/sweetalert/dist/sweetalert.css
Running talon.gen.components
* creating lib/tposs/talon/views/admin/admin-lte/components/datatable_view.ex
* creating lib/tposs/talon/templates/admin/admin-lte/components/datatable/datatable.html.slim
* creating lib/tposs/talon/templates/admin/admin-lte/components/datatable/table_body.html.slim
* creating lib/tposs/talon/views/admin/admin-lte/components/paginate_view.ex
** (ArgumentError) argument error
    :erlang.byte_size(%{app: :tposs, assets: true, base: "Tposs", binding: [alias: "Tposs", human: "Tposs", base: "Tposs", web_module: "TpossWeb", module: "Tposs.Tposs", scoped: "Tposs", singular: "tposs", path: "tposs"], boilerplate: true, brunch: false, brunch_path: "assets/brunch-config.js", components: true, concern: "Admin", concern_path: "admin", dashboard: true, dry_run: nil, generators: true, images_path: "assets/static/images", layouts: true, path_prefix: "", print_brunch_error: true, project_structure: :phx, raw_args: [], root_path: "lib/tposs/talon", target_module: "AdminLte", target_name: "admin-lte", theme: "admin-lte", vendor_parent: "assets", verbose: nil, view_opts: ", theme: \"admin/admin-lte\", module: Tposs.Admin.AdminLte.Web", web_namespace: "Web."})
    lib/mix/tasks/talon.gen.theme.ex:355: Mix.Tasks.Talon.Gen.Theme.print_brunch_instructions/1
    lib/mix/tasks/talon.new.ex:243: Mix.Tasks.Talon.New.gen_theme/1
    lib/mix/tasks/talon.new.ex:90: Mix.Tasks.Talon.New.do_run/1
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

**Comment by surik** [comment]
The same error on Phoenix 1.2

**Comment by lATAl** [comment]
Me too.
