### ISSUE TITLE
talon.new: no function clause matching in Mix.Talon.web_namespace/1

### ISSUE THREAD

**Issue by tmbb** [ex-admin/ex_admin#84]
The `mix talon.new` task crashed with the following error.

```
$ mix talon.new
** (FunctionClauseError) no function clause matching in Mix.Talon.web_namespace/1

    The following arguments were given to Mix.Talon.web_namespace/1:

        # 1
        :unknown

    Attempted function clauses (showing 2 out of 2):

        def web_namespace(-:phx-)
        def web_namespace(-:phoenix-)

    lib/mix/talon.ex:267: Mix.Talon.web_namespace/1
    lib/mix/tasks/talon.new.ex:359: Mix.Tasks.Talon.New.do_config/2
    lib/mix/tasks/talon.new.ex:75: Mix.Tasks.Talon.New.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
```

I'm using windows and a virgin Phoenix 1.3 project.

**Comment by smpallen99** [comment]
I doubt Talon will work with the released version of Phoenix 1.3. It has not be updated for the new project structure. I'm not sure when I will have time to get back to Talon dev.

**Comment by tmbb** [comment]
Ok, just reporting it. I don't have time to work on talon either right now...
